// <auto-generated />
namespace ExpertsProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class int111 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(int111));
        
        string IMigrationMetadata.Id
        {
            get { return "201612021951318_int111"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
